### ISSUE TITLE
Duplicate DataTypeTemplates when importing an ICD file, if a previous ICD import was renamed

### ISSUE THREAD

**Issue by jarradraumati** [danyill/oscd-import-templates#2]
The current import template feature seems to import duplicate DataTypeTemplates if the IED of a previous ICD import is renamed.

Steps to reproduce:

1. Start with new project
2. Import the following ICD files, 1 IED per ICD.
   - [Siprotec_6MU85_Transformer_Line.zip](https://github.com/danyill/oscd-import-templates/files/13329035/Siprotec_6MU85_Transformer_Line.zip)
   - [Siprotec_7UT85_Supply_Yd.zip](https://github.com/danyill/oscd-import-templates/files/13329041/Siprotec_7UT85_Supply_Yd.zip)
3. Renamed the 7UT85 to `XAT_T1_P2`
4. Import the 7UT85 ICD file again and create one IED
5. Validation fails 
![image](https://github.com/danyill/oscd-import-templates/assets/3224671/54eb12a7-3114-42ee-9b37-cf42599e46d6)

The resulting SCD file with the duplicates:

[2023-11-13_ICD_import_duplicate_datatypetemplates.zip](https://github.com/danyill/oscd-import-templates/files/13329077/2023-11-13_ICD_import_duplicate_datatypetemplates.zip)

The present workaround is to open the SCD file up in a text editor and manually replace the `SIEMENS_7UT85_01` with the new IED name `XAT_T1_P2`. However, this proliferates duplicate DataTypeTemplates but with different ids.

**Comment by danyill** [comment]
Good catch! I need to do some work as to why this is because I find it unexpected and confusing.

**Comment by danyill** [comment]
This has been fixed upstream and a new release has been published and incorporated into our distribution. 
Please test!
