### ISSUE TITLE
Add support for importing CID file which can contain multiple IEDs

### ISSUE THREAD

**Issue by TPChenDNZ** [danyill/oscd-import-templates#4]
Add support for importing CID file which can contain multiple IEDs.

We need this for B30.

Currently I am using the "Import IEDs" plug-in from the stock OpenSCD distribution as a workaround.

**Comment by danyill** [comment]
We now have the "Import IEDs" menu option to allow this to be achieved.

This allows direct substitution of IEDs without updating the Communication section.

See https://github.com/danyill/oscd-import-ieds
