### ISSUE TITLE
Import Template IEDs dialog cuts off number of IEDs to instantiate field

### ISSUE THREAD

**Issue by jarradraumati** [danyill/oscd-import-templates#6]
I think this is due to the IED name and description being too small.

Maybe some CSS is needed on the number field.

![image](https://github.com/danyill/oscd-import-templates/assets/3224671/8bf95f27-f617-4f12-96e7-9b91f7d298e8)

**Comment by danyill** [comment]
Hmmm... I've never seen that.

I always get:

![image](https://github.com/danyill/oscd-import-templates/assets/674783/673735ba-2376-4335-9e99-0b0732072f34)

Which browser? Perhaps a Ctrl+F5 refresh may help.

**Comment by jarradraumati** [comment]
Try this file?:

[XATBZA1P1_StandardDesign_(FW8.50).zip](https://github.com/danyill/oscd-import-templates/files/14952228/XATBZA1P1_StandardDesign_.FW8.50.zip)

**Comment by danyill** [comment]
Got it, thanks.
